### PR TITLE
optionally run anode after dimple to generate anomalous difference maps

### PR DESCRIPTION
**Pull request by rjgildea**
This adds the option --anode which will run mtz2sca/shelxc/anode at the end of a dimple job in order to generate an anomalous difference map along with a list of anomalous difference map peaks.

This will generate the additional files:
```
anom-blob*.png
anom-blob*-coot.py
coot-anom.sh
run-coot-anom.py
```
which can be used to visualise the anomalous map. If I+/- or SIGI+/- are not present in the input mtz file, then anode will not be run, even if the --anode option was requested.

```
$ dimple AUTOMATIC_DEFAULT_free.mtz 3i40 . --anode --jelly=0 --restr-cycles=2 -fpng 
Downloading 3i40 from RCSB...  done.
     ### Dimple v2.5.9. Problems and suggestions: ccp4.github.io/dimple ###
MTZ (1.5A)            I 2 3        (78.09, 78.09, 78.09,  90, 90, 90)
3I40.pdb              I 21 3       (77.22, 77.22, 77.22,  90, 90, 90)
  1 rwcontents       0.1s  24 x 6kDa (+ 1kDa het) in 460nm3, 63% solvent
  2 pointless        1.3s  resol. 1.52 A   #refl: 10952
    [-k,h,l]   CC: 0.640    cell diff: 0.9A
    [h,k,l]    CC: 0.054    cell diff: 0.9A
reindexed MTZ         I 21 3       (78.09, 78.09, 78.09,  90, 90, 90)
Rigid-body refinement with resolution 3.5 A, 10 cycles. 0.7 waters/aa.
  3 refmac5 rigid    3.4s  10/10   R  0.2616  ->  0.2446
No MR for R < 0.4.
Replace free-R flags (repeatably)
  4 unique           0.2s  
  5 freerflag        0.5s  
  6 cad              0.3s  #refl  10952 -> 12369
Restrained refinement, 0+2 cycles.
  7 refmac5 restr    8.2s   2/2   R/Rfree  0.2980/0.3045  ->  0.2449/0.2632
    RMS:   bond 0.018 -> 0.014   angle 1.31 -> 1.52   chiral 0.10 -> 0.09
  8 find-blobs       0.4s  Blob scores: 125 102 91 85 65 59 54
Rendering 2 largest blobs: at (-32.1, -3.0, -13.5) and at (-15.1, -10.5, -16.8)
  9 coot     6.4s  stdout: 4370 lines                                 
 10 render           9.4s   blob1v1.png / 11 blob1v2.png / 12 blob1v3.png
 13 render          32.2s   blob2v1.png / 14 blob2v2.png / 15 blob2v3.png
To see it in Coot run /Users/rjgildea/tmp/dimple/coot.sh
 16 mtz2sca          0.1s  stdout:   16 lines                                
 17 shelxc           0.3s  stdout:   67 lines                                
 18 anode            0.5s  20 anomalous peaks found:
Heights (sig): 22.13 17.68 14.2 14.11 11.96 11.89 11.03 10.03 6.87 6.22 5.8 5.44 5.32 4.84 4.77 4.61 4.25 4.2 4.15 4.09
Rendering 2 largest blobs: at (-13.7, -13.7, -13.7) and at (-26.1, 4.2, -17.6)
 19 coot         1.4s  stdout: 4299 lines                                 
 20 render           0.8s   anom-blob1v1.png / 21 anom-blob1v2.png / 22 anom-blob1v3.png
 23 render           1.2s   anom-blob2v1.png / 24 anom-blob2v2.png / 25 anom-blob2v3.png
```

image

### CODE REVIEW

**Comment by rjgildea** [comment]
I should have probably included some references to anode in the pull request!
ANODE: anomalous and heavy-atom density calculation, Thorn, A. & Sheldrick, G. M. (2011). J. Appl. Cryst. 44, 1285-1287.
http://shelx.uni-ac.gwdg.de/~athorn/pdf/thorn2011.pdf
http://shelx.uni-goettingen.de/anode.php
We have had requests for such a feature from some DLS beamlines, including I23. It can be useful e.g. for validation of MR solutions, and for identification of anomalous scatterers.

**Comment by wojdyr** [comment]
Sorry for almost a monthly delay.
It looks good and I'm sure it will be a useful feature.
I suppose I should add an option to disable blob searching in a normal map, so dimple can be used to just generate anomalous map.

> This will generate the additional files:
> 
> anom-blob*.png
> anom-blob*-coot.py
> coot-anom.sh
> run-coot-anom.py

These are good names, but it's a lot of scripts and files all together. Perhaps it would be neater if they all had the same prefix (anom-coot.sh instead of coot-anom.sh, anom-run-coot.py), so they are grouped together when listing a directory.


I'm just starting to test it and I'll merge it soon.

```
$ pyflakes *.py
main.py:340: local variable 'ms_job' is assigned to but never used
main.py:342: local variable 'shelxc_job' is assigned to but never used
```
this is a minor thing, I'll delete these variables later on.

I tried running it without shelx installed. It shows an error saying that shelxc is not found, but then it goes on and throws an exception ending in:
```
AttributeError: 'NoneType' object has no attribute 'rfind'
```
I think we'll need to check for shelxc and anode at the beginning and print an error message without running anything.

Now I'll install shelx and try it again.

**Comment by wojdyr** [comment]
Thanks, it works and I've merged it. Now I'll rename the output files.

I've been wondering if it's possible to generate anomalous map using mmtbx or CCP4 utilities. Then find-blobs could be used to find peaks as it is done for normal map, avoiding dependency on shelxc and anode.

**Comment by rjgildea** [comment]
Thanks! I thought that since shelxc and anode a dependency on those software was no worse than a dependency on e.g. refmac or any other CCP4 programs. But yes, I'm sure that equivalent functionality could be accomplished using mmtbx or software.

**Comment by wojdyr** [comment]
Just for the record, here are pictures from running the thaumatin example from tests subdirectory with `--anode`
anom-blob1v1
anom-blob2v1

**Comment by graeme-winter** [comment]
Disulphide bridges 🙂 👍 nice

**Comment by wojdyr** [comment]
I modified the summary of anomalous peaks to include nearby atoms for the 6 highest peaks. It now looks like this:

     13 anode            2.1s  21 anomalous peaks with height h>4 sigma
    h=29 at SG_A:CYS9  h=29 at SG_A:CYS145  h=28 at SG_A:CYS56
    h=28 at SG_A:CYS134  h=27 at SD_A:MET112  h=26 at SG_A:CYS204

or

     12 anode            1.1s  18 anomalous peaks with height h>4 sigma
    h=113 3A from NH1_A:ARG419  h=14 3A from NH1_A:ARG449  h=10 4A from CH2_A:TR
    h=10 at SD_A:MET421  h=9 at SG_A:CYS425  h=9 at SG_A:CYS353

One more thing. I remember that the DLS web interface used to show `dimple.log` as a summary of the run. If it's still the case consider changing it to `screen.log` which is more human-readable.

**Pull request merged**
