### PR TITLE
Fixed ssl error

### PR DESCRIPTION
**Pull request by hlasimpk**
- I've added in a small fix to resolve an ssl certificate error when querying contabase via urllib2.

### CODE REVIEW

**Comment by wojdyr** [comment]
Not sure if the problem is in the certificate. The file is just not there.
We have

    CONTAMINER_JSON = 'https://strube.cbrc.kaust.edu.sa/contaminer/contabase.json'

and currently the link doesn't work.
 
@dunatotatos ?

**Comment by hlasimpk** [comment]
Hmm, this was a bug I fixed just before christmas at which point the contaminer json file was available but gave a problem with the certificate.

As you say though, the contabase json file is no longer available at that address causing a new error.

**Comment by dunatotatos** [comment]
Our server crashed. I'm trying my best to get it back online, but I'm currently off campus.

**Comment by dunatotatos** [comment]
The server is fixed and back online. Sorry for the long delay, I wasn't on the campus and had no access to the administration...
Happy new year to all of you!

**Comment by wojdyr** [comment]
@dunatotatos Thanks and happy New Year.

@hlasimpk now it works for me as is, so I'm closing it.

**Comment by hlasimpk** [comment]
@wojdyr This works for me too now, I think the server fix by @dunatotatos has sorted the ssl error I was getting. Happy new year!

**Pull request closed without merging**
